on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      # NODE_OPTIONS: "--max-old-space-size=8192"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Check Code Formatting
        run: pnpm lint

      - name: Check TypeScript Types
        run: pnpm checktypes

      - name: Run Component Tests
        run: pnpm test:ci
        env:
          CI: true

      - name: Build packages
        run: pnpm build
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - uses: antfu/export-size-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_token: ${{ secrets.COMMENT_TOKEN }}
          paths: packages/core,packages/shared,packages/integrations,packages/firebase,packages/rxjs
