# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    paths:
      - "packages/**"
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      # NODE_OPTIONS: "--max-old-space-size=16384"
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Lint types and code
        run: pnpm lint

      - name: Run Component Tests
        run: pnpm test:ci
        env:
          CI: true

      - name: Build packages
        run: pnpm build

      - name: Setup CI Git User
        run: |
          git config --global user.name "codebender828"
          git config --global user.email "jbakebwa@163.com"

      - name: Create Release Pull Request
        uses: changesets/action@master
        with:
          publish: pnpm release
          title: "chore(release): version packages and publish"
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
